
program
    : block
    ;

block
    : '{' blockItem* '}'
    ;

blockItem
    : declaration
    | statement
    ;

declaration
    : 'int' IDENTIFIER ';' # for now
    ;

statement
    : assignmentStatement
    | ifStatement
    | block
    ;

assignmentStatement
    : IDENTIFIER '=' expression ';'
    ;

ifStatement
    : 'if' '(' expression ')' statement ('else' statement)?
    ;

expression
    : term (('+' | '-') term)*
    ;

term
    : factor (('*' | '/') factor)*
    ;

factor
    : '(' expression ')'
    | IDENTIFIER
    | NUMBER
    ;
