program
    : block
    ;

block
    : '{' blockItem* '}'
    ;

blockItem
    : declaration
    | statement
    ;

declaration
    : 'int' IDENTIFIER ';' # for now
    ;

statement
    : expressionStatement
    | returnStatement
    | ifStatement
    | whileStatement
    | block
    ;

expressionStatement
    : expression ';'
    ;

returnStatement
    : 'return' expression ';'
    ;

ifStatement
    : 'if' '(' expression ')' statement ('else' statement)?
    ;

whileStatement
    : 'while' '(' expression ')' statement
    ;

expression
    : assignmentExpression
    ;

assignmentExpression
    : IDENTIFIER '=' equalityExpression
    | equalityExpression
    ;

equalityExpression
    : relationalExpression (('==' | '!=') relationalExpression)*
    ;

relationalExpression
    : additiveExpression (('>' | '>=' | '<' | '<=') additiveExpression)*

additiveExpression
    : multiplicativeExpression (('+' | '-') multiplicativeExpression)*
    ;

multiplicativeExpression
    : postfixExpression (('*' | '/' | '%') postfixExpression)*
    ;

postfixExpression
    : primary
    ;

primary
    : '(' expression ')'
    | IDENTIFIER
    | NUMBER
    ;